resources:
  - ../base/namespace.yaml
  - ../base/postgres.yaml
  - ../base/helpdesk.yaml

configMapGenerator:
  - name: helpdesk-site
    namespace: helpdesk
    literals:
      - SITE_ROLE=standby
      - SITE_NAME=on-prem
      - DR_READY_POLICY=flag
      - DR_ACTIVE=false
  - name: helpdesk-automation
    namespace: helpdesk
    literals:
      - AUTOMATION_MODE=lambda-dr
      - LAMBDA_DR_BASE_URL=http://event-adapter.lambda-dr.svc.cluster.local:8080
