apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - event-adapter.yaml
  - helpdesk-ticket-processor.yaml
  - sample-orders-function.yaml
  - sample-payments-function.yaml
  - sample-reports-function.yaml
  - network-policy.yaml
