apiVersion: v1
kind: ServiceAccount
metadata:
  name: helios-web
  namespace: helios-desk
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helios-bff
  namespace: helios-desk
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_BFF_IRSA_ROLE_ARN
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helios-ticket-service
  namespace: helios-desk
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_TICKET_IRSA_ROLE_ARN
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helios-automation-service
  namespace: helios-desk
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_AUTOMATION_IRSA_ROLE_ARN
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helios-postgres-backup
  namespace: helios-desk
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_BACKUP_IRSA_ROLE_ARN
automountServiceAccountToken: true
