from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol

from helios_bff.domain.auth import BrowserSession, OAuthTransaction, TokenSet
from helios_bff.domain.telemetry import DrTelemetryRecord


class AuthStore(Protocol):
    async def save_transaction(self, transaction: OAuthTransaction) -> None: ...

    async def consume_transaction(self, state_hash: str) -> OAuthTransaction | None: ...

    async def save_session(self, session: BrowserSession) -> None: ...

    async def get_session(self, session_id_hash: str) -> BrowserSession | None: ...

    async def delete_session(self, session_id_hash: str) -> None: ...

    async def ping(self) -> bool: ...


class SecretProtector(Protocol):
    def encrypt(self, value: str) -> str: ...

    def decrypt(self, value: str) -> str: ...


class OidcBrowserClient(Protocol):
    def authorization_url(self, *, state: str, nonce: str, code_challenge: str) -> str: ...

    async def exchange_code(self, *, code: str, code_verifier: str) -> TokenSet: ...

    def end_session_url(self) -> str: ...


class TicketClient(Protocol):
    async def list_tickets(self, access_token: str) -> dict[str, Any]: ...

    async def get_ticket(self, access_token: str, ticket_id: str) -> dict[str, Any]: ...

    async def create_ticket(
        self, access_token: str, payload: Mapping[str, Any]
    ) -> dict[str, Any]: ...

    async def update_ticket(
        self, access_token: str, ticket_id: str, payload: Mapping[str, Any]
    ) -> dict[str, Any]: ...

    async def delete_ticket(self, access_token: str, ticket_id: str) -> None: ...

    async def ping(self) -> bool: ...


class AutomationClient(Protocol):
    async def run_ticket_automation(
        self, access_token: str, event: Mapping[str, Any]
    ) -> dict[str, Any]: ...

    async def ping(self) -> bool: ...


class DrTelemetryStore(Protocol):
    async def read(self, metrics: Sequence[str]) -> Mapping[str, DrTelemetryRecord]: ...


class PlatformProbe(Protocol):
    async def status(self) -> dict[str, Any]: ...

    async def ping(self) -> bool: ...
