apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: helpdesk
  namespace: helios-desk
spec:
  dnsZone: heliospoc.ggg.it
  strategy:
    type: failover
    primaryGeoTag: cloud
  ingress:
    ingressClassName: traefik
    rules:
      - host: heliospoc.ggg.it
        http:
          paths:
            - path: /api
              pathType: Prefix
              backend:
                service:
                  name: helios-bff
                  port:
                    number: 8000
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: helios-web
                  port:
                    number: 8080
