events {
    worker_connections 1024;
}

http {
    resolver 172.28.20.250 valid=5s ipv6=off; # Usa il server-dns nella DMZ per risolvere il GSLB

    server {
        listen 80 default_server;
        server_name _;

        location = /router-health {
            access_log off;
            default_type application/json;
            return 200 '{"status":"up","component":"boundary-router"}\n';
        }

        location / {
            return 444;
        }
    }

    include /etc/nginx/conf.d/*.conf;
}

stream {
    server {
        listen 53 udp;
        listen 53;
        proxy_pass server-dns:53;
        proxy_timeout 10s;
        proxy_responses 1;
    }
}
