http_port 3128

acl employee_network src 172.28.10.0/24
acl dmz_network src 172.28.20.0/24
acl private_destination dst 10.0.0.0/8
acl private_destination dst 172.16.0.0/12
acl private_destination dst 192.168.0.0/16
acl private_destination dst 169.254.0.0/16
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny private_destination
http_access allow employee_network
http_access allow dmz_network
http_access deny all

cache deny all
access_log none
cache_log /dev/null
pid_filename /tmp/squid.pid
