resources:
  - ../base/namespace.yaml
  - ../base/postgres.yaml
  - ../base/helpdesk.yaml

configMapGenerator:
  - name: helpdesk-site
    namespace: helpdesk
    literals:
      - SITE_ROLE=primary
      - SITE_NAME=cloud-sim
      - DR_READY_POLICY=always
      - DR_ACTIVE=false
  - name: helpdesk-automation
    namespace: helpdesk
    literals:
      - AUTOMATION_MODE=aws-lambda
      - AWS_ENDPOINT_URL=http://localstack.helpdesk.svc.cluster.local:4566
